### ISSUE TITLE
连不上网了

### ISSUE THREAD

**Issue by WHITE13452** [josephstalin117/lgn_bjut_script#2]
emmm我在本地跑了一下脚本，然后连接失败，但是跑脚本的时候是连接网络的状态之后就一直没法注销了，也没法上网，请问有什么办法吗

**Comment by josephstalin117** [comment]
注销可以使用logout脚本再跑一遍就可以了，如果显示连接失败要看下报错，看下$gno变量显示什么？改成相应的gno变量就可以
```
#if [ "$gno" == "Gno=01" ]; then
if [ "$gno" == "Gno=44" ]; then
    echo "login_success"
```

**Comment by WHITE13452** [comment]
感谢回复，之前已经自己解决了，谢谢！




怀特
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "josephstalin117/lgn_bjut_script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 晚上9:51
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [josephstalin117/lgn_bjut_script] 连不上网了 (Issue #2)





 
注销可以使用logout脚本再跑一遍就可以了，如果显示连接失败要看下报错，看下$gno变量显示什么？改成相应的gno变量就可以
 #if [ "$gno" == "Gno=01" ]; then if [ "$gno" == "Gno=44" ]; then     echo "login_success"
